INSERT INTO EMP_DTLS (EMP_ID, DEPT_ID, FIRST_NAME, LAST_NAME, SALARY) VALUES (01,01, 'Stuart', 'Little', 1034300.100);
INSERT INTO EMP_DTLS (EMP_ID, DEPT_ID, FIRST_NAME, LAST_NAME, SALARY) VALUES (02,02, 'Arundhati', 'Roy', 154000.100);
INSERT INTO EMP_DTLS (EMP_ID, DEPT_ID, FIRST_NAME, LAST_NAME, SALARY) VALUES (03,03, 'JC', 'Bose', 1033400.100);
INSERT INTO EMP_DTLS (EMP_ID, DEPT_ID, FIRST_NAME, LAST_NAME, SALARY) VALUES (04,02, 'Salman', 'Rushdie', 1034300.100);
INSERT INTO EMP_DTLS (EMP_ID, DEPT_ID, FIRST_NAME, LAST_NAME, SALARY) VALUES (05,05, 'Leonardo', 'da Vinci', 1034300.100);

INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_SHORT_DESC, DEPT_LONG_DESC) VALUES (01, 'IT', 'Information Technology');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_SHORT_DESC, DEPT_LONG_DESC) VALUES (02, 'Lit', 'Literature');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_SHORT_DESC, DEPT_LONG_DESC) VALUES (03, 'Stat', 'Statistics');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_SHORT_DESC, DEPT_LONG_DESC) VALUES (04, 'Psy', 'Psychology');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_SHORT_DESC, DEPT_LONG_DESC) VALUES (05, 'Arch', 'Architecture');